### 0. Recommended Import Convention

In [2]:
import numpy as np

### 1. Numpy Basics
+ The main object is a multidimensional array. => ndarray
+ All of the same type

In [3]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

#### 1.1 np.arange

In [5]:
a = np.arange(15)
print("\n a  \n", a)


 a  
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### 1.2) Np.reshape

In [6]:
a = a.reshape(3,5)
print("\n a.reshape(3,5)  \n", a)


 a.reshape(3,5)  
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### 1.3) Np.ndim

In [7]:
print("\n a.ndim \n", a.ndim)


 a.ndim 
 2


#### 1.4) Np.dtype.name

In [8]:
print("\n a.dtype.name \n",a.dtype.name)


 a.dtype.name 
 int32


#### 1.5) Np. itemsize
+ show the bytes of array element

In [9]:
print("\n a.itemsize\n",a.itemsize)


 a.itemsize
 4


#### 1.6) Np.size
+ the number of array element

In [10]:
print("\na.size\n",a.size)


a.size
 15


#### 1.7) Type(np)

In [11]:
print("\ntype(a)\n",type(a))


type(a)
 <class 'numpy.ndarray'>


### 2. Array Creation

#### 2.1) Np.zeros

In [12]:
print("\nnp.zeros(3,4)\n",np.zeros((3,4)))


np.zeros(3,4)
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 2.2) Np.ones

In [13]:
print("\nnp.ones(2,3,4)\n",np.ones((2,3,4), dtype = np.int16))


np.ones(2,3,4)
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


#### 2.3) Np.empty

In [14]:
print("\nnp.empty(2,3)\n",np.empty((2,3)))


np.empty(2,3)
 [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


#### 2.4) Np.arange
+ np.arange(a, b, c) ==> a이상 b미만 c step씩.

In [15]:
print("\nnp.arange(10, 30, 5)\n",np.arange(10,30,5) )
print("\nnp.arange(0, 2, 0.3)\n",np.arange(0,2,0.3) )


np.arange(10, 30, 5)
 [10 15 20 25]

np.arange(0, 2, 0.3)
 [0.  0.3 0.6 0.9 1.2 1.5 1.8]


#### 2.5) Np.linspace
+ arange()는 정확히 몇개의 element가 나올지 계산이 힘듦 -> linspace()를 사용해보자.
+ linspace(a, b, c) ==> a이상 b이하 c개

In [16]:
from numpy import pi
print("\n np.linspace(0, 2, 9)\n",np.linspace(0, 2, 9))

x = np.linspace(0, 2 * pi, 100) #아래 sin함수에서 0~2pi 사이 많은 point들을(100개) 생성할때 유용하다.
f = np.sin(x)
#print("\nf = np.sin(x)\n", f)


 np.linspace(0, 2, 9)
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### 3. Basic Operations

#### 3.1) - operation

In [17]:
a = np.array([20, 30, 40, 50])
print("\n a\n",a)

b = np.arange(4)
print("\n b\n",b)

c = a - b
print("\n a - b\n",c)


 a
 [20 30 40 50]

 b
 [0 1 2 3]

 a - b
 [20 29 38 47]


#### 3.2) ** operation

In [18]:
print("\n b**2\n",b**2)


 b**2
 [0 1 4 9]


#### 3.3) Np.sin

In [19]:
print("\n 10 * np.sin(a)\n",10 * np.sin(a))


 10 * np.sin(a)
 [ 9.12945251 -9.88031624  7.4511316  -2.62374854]


#### 3.4) Inequality sign

In [20]:
print("\n a < 35\n",a < 35)


 a < 35
 [ True  True False False]


#### 3.5) Diverse kinds of product

In [21]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print("\nA * B (elementwise product)\n",A * B)     # elementwise product

print("\nA.dot(B) (another matrix product)\n", A.dot(B))  # another matrix product


A * B (elementwise product)
 [[2 0]
 [0 4]]

A.dot(B) (another matrix product)
 [[5 4]
 [3 4]]


#### 3.6) Operation between two matrices

In [22]:
rg = np.random.default_rng(1) # use random number generator, provides access to a wide range of distributions
a = np.ones((2,3), dtype = int)
b = rg.random((2,3))

print("\na\n",a)

print("\nb\n",b)

a *= 3
print("\na\n",a)

b += a
print("\nb\n",b)


a
 [[1 1 1]
 [1 1 1]]

b
 [[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]

a
 [[3 3 3]
 [3 3 3]]

b
 [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


#### 3.7) Sum, min, max operations

In [25]:
a = rg.random((2, 3))
print("\na\n",a)

print("\na.sum()\n",a.sum())
print("\na.min()\n",a.min())
print("\na.max()\n",a.max())


a
 [[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]

a.sum()
 3.1057109529998157

a.min()
 0.027559113243068367

a.max()
 0.8277025938204418
